# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jMlflHdY4mc4MHageicodWbw0giap4Lu
"""

class Tennis:
    def __init__(self, nombre, edad, equipo, posicion, altura):
        self.nombre = "Roger"
        self.edad = int(19)
        self.oponente = "Rafael Nadal"
        self.marca_raqueta = "Wilson"
        self.altura = float(1.88)

    def imprimir_datos(self):
        print(f"nombre: {self.nombre}, edad: {self.edad}, oponente: {self.oponente}, marca_raqueta: {self.marca_raqueta}, Altura: {self.altura}")

    def Recibir_drive(self):
        print("el jugador recibio el drive")

    def backhand(self):
        print("El jugador recibio con un backhand")

    def golpe_con_dos_manos(self):
        print("El jugador ha golpeado con dos manos la pelota")

    def out(self):
        print("El jugador ha mandado la pelota por fuera de la cancha")

    def servicio(self):
        print("El jugador ha iniciado el rally con un saque")

c1 = Tennis("Roger", 19, "Rafael Nadal", "Wilson", 1.80)
c1.Recibir_drive()
c1.backhand()
c1.golpe_con_dos_manos()

class Partido:
    def __init__(self, nombre, edad, equipo, posicion, altura):
        self.nombre = "pedro"
        self.edad = int(25)
        self.equipo = "LA"
        self.posicion = "tirador"
        self.altura = float(1.80)

    def imprimir_datos(self):
        print(f"Nombre: {self.nombre}, Edad: {self.edad}, Equipo: {self.equipo}, Posición: {self.posicion}, Altura: {self.altura}")

    def capturar_rebote(self):
        print("el jugador hizo un rebote")

    def tapon(self):
        print("El jugador lo taponeó")

    def bloqueo(self):
        print("El jugador ha bloqueado el tiro")

    def pantalla(self):
        print("El jugador ha hecho pantalla")

    def robar(self):
        print("El jugador ha robado el balón")

c1 = Partido("pedro", 25, "LA", "tirador", 1.80)
c1.capturar_rebote()
c1.tapon()
c1.bloqueo()

class Basketball:
    def __init__(self, nombre, edad, equipo, posicion, altura):
        self.nombre = "juanes"  # Use self to assign attributes
        self.edad = int(16)
        self.equipo = "lakers"
        self.posicion = "alero"
        self.altura = float(5.11)

    def imprimir_datos(self):
        print(f"Nombre: {self.nombre}, Edad: {self.edad}, Equipo: {self.equipo}, Posición: {self.posicion}, Altura: {self.altura}")

    def saltar(self):
        print("el jugador salta")

    def pase(self):
        print(" pase en profundidad")

    def tiro(self):
        print("tiro de 3 puntos")

    def bloqueo(self):
        print("bloquear al jugador")

    def driblar(self):
        print("dribla al jugador")

c1 = Basketball("juanes", 16, "lakers", "alero", 5.11)
c1.saltar()
c1.pase()
c1.tiro()